[settings]
env_cache = true

[tools]
azure-cli = "latest"
azure-kubelogin = "latest"
claude-code = "latest"
flux-operator = "latest"
flux-operator-mcp = "latest"
flux2 = "latest"
gemini = "latest"
gh = "latest"
go = "latest"
grafana-kubernetes-plugin = "latest"
helm = "latest"
istioctl = "latest"
jq = "latest"
kind = "latest"
kubecolor = "latest"
kubeconform = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
kustomize = "latest"
kyverno = "latest"
node = "latest"
npm = "latest"
opencode = "latest"
pipx = "latest"
python = "latest"
sloth = "latest"
sops = "latest"
terraform = "latest"
vault = "latest"
yq = "latest"
